### ISSUE TITLE
Uncaught TypeError: Cannot read property 'baseURL' of undefined

### ISSUE THREAD

**Issue by danrasmuson** [capaj/jspm-dev-buddy#4]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.4.1
**System**: Mac OS X 10.10.5
**Thrown From**: [jspm-dev-buddy](https://github.com/capaj/jspm-dev-buddy) package, v0.1.1
### Stack Trace

Uncaught TypeError: Cannot read property 'baseURL' of undefined

```
At /Users/danielrasmuson/.atom/packages/jspm-dev-buddy/lib/file-saved-emitter.js:11

TypeError: Cannot read property 'baseURL' of undefined
    at /Users/danielrasmuson/.atom/packages/jspm-dev-buddy/lib/file-saved-emitter.js:11:41
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```
### Commands

```
     -0:42.4.0 core:move-right (atom-text-editor.editor.mini.is-focused)
  2x -0:40.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:38.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 15x -0:36.6.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:12 core:cancel (ul.list-inline.tab-bar.inset-panel)
     -0:11.6.0 fuzzy-finder:toggle-file-finder (ul.list-inline.tab-bar.inset-panel)
     -0:11.5.0 blur (ul.list-inline.tab-bar.inset-panel)
     -0:09.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -0:09.9.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:09.4.0 linter:lint (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:07.6.0 command-palette:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:07.5.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:04.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:04.5.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:04.5.0 jspm-dev-buddy:start (atom-text-editor.editor.vim-mode.normal-mode)
  3x -0:02.3.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "vim-surround",
      "wrap-guide",
      "linter-jshint",
      "markdown-toc"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai-dark"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
advanced-open-file, v0.12.3
atom-typescript, v7.12.1
autocomplete-paths, v1.0.2
emmet, v2.3.15
highlight-selected, v0.11.1
jspm-dev-buddy, v0.1.1
language-powershell, v2.1.0
linter, v1.11.3
markdown-table-formatter, v2.5.5
minimap, v4.16.2
monokai-dark, v1.3.0
project-manager, v2.6.5
tasks, v2.6.0
vim-mode, v0.63.0
wakatime, v5.0.1

# Dev
No dev packages
```

**Comment by danrasmuson** [comment]
I started on port 8090

**Comment by TomiS** [comment]
I seem to have the same issue.

**Comment by capaj** [comment]
this will want to update the dependency of chokidar-socket-emitter

**Comment by LennyPenny** [comment]
Same here!

**Comment by capaj** [comment]
do you have package.json in your project with baseUrl property defined? @danielrasmuson @TomiS @LennyPenny 
like here: https://github.com/capaj/jspm-react/blob/master/package.json#L28

**Comment by LennyPenny** [comment]
That fixed it thanks! 
Probably should add that to `jspm init`
